@set allusersprofile=c:\programdata
@set appdata=c:\users\eligantru\appdata\roaming
@set commonprogramfiles=c:\program files\common files
@set commonprogramfiles(x86)=c:\program files (x86)\common files
@set commonprogramw6432=c:\program files\common files
@set computername=home
@set comspec=c:\windows\system32\cmd.exe
@set farhome=e:\far
@set farlang=english
@set farlocalprofile=c:\users\eligantru\appdata\local\far manager\profile
@set farprofile=c:\users\eligantru\appdata\roaming\far manager\profile
@set fp_no_host_check=no
@set homedrive=c:
@set homepath=\users\eligantru
@set localappdata=c:\users\eligantru\appdata\local
@set logonserver=\\microsoftaccount
@set msbuildloadmicrosofttargetsreadonly=true
@set msbuildsdkspath=e:\visualstudio\msbuild\sdks
@set msbuild_exe_path=e:\pvs-studio\buildtools15\msbuild.exe
@set number_of_processors=8
@set onlineservices=online services
@set os=windows_nt
@set path=e:\python\scripts\;e:\python\;c:\program files (x86)\intel\icls client\;c:\program files\intel\icls client\;c:\program files (x86)\nvidia corporation\physx\common;c:\windows\system32;c:\windows;c:\windows\system32\wbem;c:\windows\system32\windowspowershell\v1.0\;c:\program files (x86)\windows live\shared;c:\program files\intel\intel(r) management engine components\dal;c:\program files\intel\intel(r) management engine components\ipt;c:\program files (x86)\intel\intel(r) management engine components\dal;c:\program files (x86)\intel\intel(r) management engine components\ipt;c:\program files\intel\wifi\bin\;c:\program files\common files\intel\wirelesscommon\;c:\program files\hewlett-packard\simplepass\;c:\program files (x86)\skype\phone\;e:\nodejs\;e:\cmake\bin;e:\git\bin;c:\users\eligantru\appdata\roaming\npm;c:\users\eligantru\appdata\local\atom\bin;c:\users\eligantru\appdata\local\githubdesktop\bin
@set pathext=.com;.exe;.bat;.cmd;.vbs;.vbe;.js;.jse;.wsf;.wsh;.msc;.py;.pyw
@set pcbrand=pavilion
@set pkgdefapplicationconfigfile=c:\users\eligantru\appdata\local\microsoft\visualstudio\15.0_769d62c5\devenv.exe.config
@set platform=mcd
@set processor_architecture=amd64
@set processor_identifier=intel64 family 6 model 60 stepping 3, genuineintel
@set processor_level=6
@set processor_revision=3c03
@set programdata=c:\programdata
@set programfiles=c:\program files
@set programfiles(x86)=c:\program files (x86)
@set programw6432=c:\program files
@set prompt=$p$g
@set psmodulepath=c:\windows\system32\windowspowershell\v1.0\modules\
@set public=c:\users\public
@set pvsbuildtoolsextensionspath=e:\visualstudio\msbuild
@set pvs_vsinstalldir=e:\visualstudio
@set sessionname=console
@set systemdrive=c:
@set systemroot=c:\windows
@set temp=c:\users\eligan~1\appdata\local\temp
@set tmp=c:\users\eligan~1\appdata\local\temp
@set userdomain=home
@set userdomain_roamingprofile=home
@set username=eligantru
@set userprofile=c:\users\eligantru
@set visualstudiodir=c:\users\eligantru\documents\visual studio 2017
@set visualstudioedition=microsoft visual studio community 2017
@set visualstudioversion=15.0
@set vsappiddir=e:\visualstudio\common7\ide\
@set vsappidname=devenv.exe
@set vslang=1033
@set windir=c:\windows
@set vs140comntools=C:\Program Files (x86)\Microsoft Visual Studio\Shared\14.0\Common7\Tools\

@call cl.exe